// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XHNNg7u_blut2TloqmeM8m7Ao8OaJ4M',
    appId: '1:840786438866:web:e7290196111751f5c51b0b',
    messagingSenderId: '840786438866',
    projectId: 'smart-water-scheduler',
    authDomain: 'smart-water-scheduler.firebaseapp.com',
    storageBucket: 'smart-water-scheduler.firebasestorage.app',
    measurementId: 'G-P7RE0CE5K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAv3A7u6rdH7M-LoYtxIod_tGK6tPYB8k',
    appId: '1:840786438866:android:7b687d06e7ed2453c51b0b',
    messagingSenderId: '840786438866',
    projectId: 'smart-water-scheduler',
    storageBucket: 'smart-water-scheduler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbmFYEhJkK-fXsyDjFJWjDcGnWdgpWNs',
    appId: '1:840786438866:ios:5c1a87d306382207c51b0b',
    messagingSenderId: '840786438866',
    projectId: 'smart-water-scheduler',
    storageBucket: 'smart-water-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.smartWaterScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbmFYEhJkK-fXsyDjFJWjDcGnWdgpWNs',
    appId: '1:840786438866:ios:5c1a87d306382207c51b0b',
    messagingSenderId: '840786438866',
    projectId: 'smart-water-scheduler',
    storageBucket: 'smart-water-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.smartWaterScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9XHNNg7u_blut2TloqmeM8m7Ao8OaJ4M',
    appId: '1:840786438866:web:3162dae1f4275f2cc51b0b',
    messagingSenderId: '840786438866',
    projectId: 'smart-water-scheduler',
    authDomain: 'smart-water-scheduler.firebaseapp.com',
    storageBucket: 'smart-water-scheduler.firebasestorage.app',
    measurementId: 'G-874142KX4S',
  );
}
